const express = require('express')
const controller = require('./controller')
const report = require('./report')
const duty = require('./duty')
const { requirePermission } = require('../../middleware/auth')

const router = express.Router()

router.get('/duty/setup', requirePermission('attendance.duty.manage', 'attendance.duty.admin.approve'), duty.setup)
router.put('/duty/setup/:year', requirePermission('attendance.duty.manage'), duty.saveSetup)
router.get('/duty/monthly', requirePermission('attendance.duty.manage', 'attendance.duty.admin.approve'), duty.monthly)
router.put('/duty/records/:id/overlap', requirePermission('attendance.duty.manage'), duty.resolveOverlap)
router.post('/duty/monthly/:month/submit', requirePermission('attendance.duty.manage'), duty.submit)
router.post('/duty/monthly/:month/approve', requirePermission('attendance.duty.admin.approve'), duty.approve)
router.post('/duty/monthly/:month/reject', requirePermission('attendance.duty.admin.approve'), duty.reject)
router.get('/duty/batches', requirePermission('attendance.duty.manage', 'attendance.duty.admin.approve'), (req, res) =>
  duty.listMonthlyBatches(String(req.query.status || '')).then((items) => res.json({ items })).catch((error) => { throw error }))

router.get('/employees', requirePermission('attendance.view', 'attendance.manage', 'attendance.admin.approve'), controller.listEmployees)
router.get('/delegates', requirePermission('attendance.apply'), controller.listDelegates)
router.get('/me', requirePermission('attendance.apply', 'attendance.approve', 'attendance.view', 'attendance.manage', 'attendance.admin.approve'), controller.me)
router.get('/me/balance-ledger', requirePermission('attendance.apply'), controller.myBalanceLedger)
router.get('/supervisor-role-rules', requirePermission('attendance.view', 'attendance.manage', 'attendance.admin.approve'), controller.listSupervisorRoleRules)
router.put('/supervisor-role-rules', requirePermission('attendance.manage'), controller.updateSupervisorRoleRules)
router.get('/approval-role-rules', requirePermission('attendance.view', 'attendance.manage', 'attendance.admin.approve'), controller.listApprovalRoleRules)
router.put('/approval-role-rules', requirePermission('attendance.manage'), controller.updateApprovalRoleRules)
router.get('/legal-holidays', requirePermission('attendance.apply', 'attendance.approve', 'attendance.view', 'attendance.manage', 'attendance.admin.approve'), controller.listLegalHolidays)
// 假别元数据（spec 004）：读取供申请下拉/列表 label；?all=1 含停用项仅 manage 生效
router.get('/leave-types', requirePermission('attendance.apply', 'attendance.approve', 'attendance.view', 'attendance.manage', 'attendance.admin.approve'), controller.listLeaveTypes)
router.post('/leave-types', requirePermission('attendance.manage'), controller.createLeaveTypeHandler)
router.put('/leave-types/:id', requirePermission('attendance.manage'), controller.updateLeaveTypeHandler)
router.delete('/leave-types/:id', requirePermission('attendance.manage'), controller.deleteLeaveTypeHandler)
router.put('/legal-holidays/:date', requirePermission('attendance.manage'), controller.upsertLegalHoliday)
router.delete('/legal-holidays/:date', requirePermission('attendance.manage'), controller.deleteLegalHoliday)
router.post('/legal-holidays/sync-preview', requirePermission('attendance.manage'), controller.syncLegalHolidaysPreview)
router.post('/legal-holidays/sync-confirm', requirePermission('attendance.manage'), controller.syncLegalHolidaysConfirm)
router.put('/employees/:id', requirePermission('attendance.manage'), controller.updateEmployee)
router.post('/employees/batch-balance-init', requirePermission('attendance.manage'), controller.batchInitBalance)
router.post('/employees/:id/adjust-balance', requirePermission('attendance.manage'), controller.adjustBalance)

router.get('/requests', requirePermission('attendance.apply', 'attendance.approve', 'attendance.view', 'attendance.manage', 'attendance.admin.approve'), controller.listRequests)
router.get('/requests/pending-count', requirePermission('attendance.approve', 'attendance.view', 'attendance.manage', 'attendance.admin.approve', 'attendance.hr.approve', 'attendance.vp.approve'), controller.pendingApprovalCount)
router.post('/requests', requirePermission('attendance.apply'), controller.createRequest)
router.post('/requests/:id/submit', requirePermission('attendance.apply'), controller.submitRequest)
router.get('/overtime/service-orders', requirePermission('attendance.apply'), controller.listOvertimeServiceOrders)
router.post('/overtime/service-orders/:id/apply', requirePermission('attendance.apply'), controller.createServiceOrderOvertimeRequest)
router.post('/requests/:id/approve-delegate', requirePermission('attendance.approve'), controller.approveDelegate)
router.post('/requests/:id/approve-supervisor', requirePermission('attendance.approve', 'attendance.view'), controller.approveSupervisor)
router.post('/requests/:id/approve-hr', requirePermission('attendance.hr.approve'), controller.approveHr)
router.post('/requests/:id/approve-vp', requirePermission('attendance.vp.approve'), controller.approveVp)
router.post('/requests/:id/approve', requirePermission('attendance.approve', 'attendance.view', 'attendance.manage', 'attendance.admin.approve'), controller.approveRole)
router.post('/requests/:id/approve-admin', requirePermission('attendance.admin.approve'), controller.approveAdmin)
router.post('/requests/:id/reject', requirePermission('attendance.approve', 'attendance.view', 'attendance.manage', 'attendance.admin.approve'), controller.rejectRequest)
router.post('/requests/:id/withdraw', requirePermission('attendance.apply'), controller.withdrawRequest)
router.post('/requests/:id/void', requirePermission('attendance.admin.approve'), controller.voidRequest)

router.get('/reports/monthly', requirePermission('attendance.view', 'attendance.admin.approve', 'attendance.manage'), controller.monthlyReport)
router.get('/reports/export', requirePermission('attendance.report.export'), report.exportReport)

module.exports = router
