const express = require('express')
const controller = require('./controller')
const { requirePermission } = require('../../middleware/auth')

const router = express.Router()

router.get('/constants', requirePermission('mr.view'), controller.getConstants)
router.get('/assistant-setting', requirePermission('mr.view'), controller.getAssistantSetting)
router.put('/assistant-setting', requirePermission('mr.view'), controller.setAssistantSetting)
router.get('/layout-rules', requirePermission('mr.view'), controller.listLayoutRules)
router.post('/layout-rules', requirePermission('mr.edit'), controller.createLayoutRule)
router.put('/layout-rules/:id', requirePermission('mr.edit'), controller.updateLayoutRule)
router.delete('/layout-rules/:id', requirePermission('mr.edit'), controller.deleteLayoutRule)
router.get('/', requirePermission('mr.view'), controller.list)
router.get('/import-progress', requirePermission('mr.view'), controller.importProgressHandler)
router.get('/vendor-suggestions', requirePermission('mr.view'), controller.vendorSuggestions)
router.post('/', requirePermission('mr.create'), controller.create)
router.get('/:id', requirePermission('mr.view'), controller.detail)
router.put('/:id', requirePermission('mr.edit'), controller.update)
router.post('/:id/submit', requirePermission('mr.edit'), controller.submit)
router.post('/:id/approve', requirePermission('mr.approve'), controller.approve)
router.post('/:id/reject', requirePermission('mr.approve'), controller.reject)
router.post('/:id/reassign-sales', requirePermission('mr.edit'), controller.reassignSalesOwner)
router.post('/:id/withdraw', requirePermission('mr.edit'), controller.withdraw)
router.post('/:id/void', requirePermission('mr.void'), controller.voidOrder)
router.put('/:id/purchase', requirePermission('mr.purchase'), controller.submitPurchase)
router.post('/:id/import', requirePermission('mr.edit'), controller.quotationUpload, controller.importQuotation)
router.post('/:id/attachments', requirePermission('mr.edit'), controller.attachmentUpload, controller.uploadAttachments)
router.get('/:id/quotation', requirePermission('mr.view'), controller.downloadQuotation)
router.delete('/:id/quotation', requirePermission('mr.edit'), controller.deleteQuotationFile)
router.get('/:id/document', requirePermission('mr.view'), controller.downloadDocument)
router.delete('/:id', requirePermission('mr.delete'), controller.remove)

module.exports = router
